name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          cache: true

      - name: Check Flutter & Dart Versions
        run: |
          flutter --version
          dart --version  # Verify Dart SDK version

      - name: Install dependencies
        run: flutter pub get  # Install Flutter dependencies

      - name: Run unit tests
        run: flutter test test/unit  # Run all unit tests

      - name: Run widget tests
        run: flutter test test/widget  # Run all widget tests
