name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.0.0

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test test/unit

      - name: Run widget tests
        run: flutter test test/widgets